version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.17.10-alpine
    entrypoint: "init.sh"
    environment:
      - DOMAIN_SERVICES=${DOMAIN_SERVICES}
    volumes:
      - ./config/init.sh:/usr/local/bin/init.sh
      - ${SSL_KEY_PATH}:/etc/.certs/server.key
      - ${SSL_CERT_PATH}:/etc/.certs/server.crt
    ports:
      - 80:80
      - 443:443
    networks:
      - net-nginx

networks:
  net-nginx:
    name: net-nginx
    driver: bridge
    driver_opts:
      encrypted: "true"
#  net-nginx:
#    external: true
#    name: net-nginx
#    driver: overlay
#    driver_opts:
#      encrypted: "true"
# docker network connect [network name] [container name]


